language: python
sudo: false

python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq graphviz

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls

script:
  python runtests.py --cov=.

after_success:
  coveralls
