language: python
sudo: false

python:
  - "2.7"

addons:
  apt:
    packages:
    - graphviz

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls

script:
  python runtests.py --cov=.

after_success:
  coveralls
