language: python
sudo: false

python:
  - "2.7"

addons:
  apt:
    packages:
    - graphviz

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  py.test --cov=pydeps

after_success:
  coveralls
