language: python
sudo: false

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

jobs:
  allow_failures:
    - python: "3.8"

addons:
  apt:
    packages:
    - graphviz

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  py.test -vv --cov=pydeps .

after_success:
  coveralls
